# Dependencies
# markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Kshitij Shah'
tagline:          'Data Scientist'
description:      'MSCS student at Rutgers, Data Scientist'
url:              https://xitizzz.github.io
baseurl:          /typo

email: kshitij.shah.cs@gmail.com
github_username:  xitizzz
linkedin_public_url: kshitij-shah-cs

author:
  name:           'Kshitij '
  url:            https://twitter.com/xitizzz

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://xitizzz.github.io/typo


